version: 1.0 
os: linux 

files:
  - source: /             
    destination: /var/www/html  

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh 
      timeout: 300
  AfterInstall:
    - location: scripts/start_server.sh  
      timeout: 300
  ApplicationStart:
    - location: scripts/restart_server.sh  
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh  
      timeout: 300