version: 0.0 
os: linux 

files:
  - source: /             
    destination: /var/www/aws-chat

hooks:
  BeforeInstall:
    - location: unzip_artifact.sh
      timeout: 60
  AfterInstall:
    - location: start_server.sh
      timeout: 60
  ApplicationStart:
    - location: restart_server.sh
      timeout: 60
  ValidateService:
    - location: validate_service.sh
      timeout: 60