version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix app

  build:
    commands:
      - echo "Building the Angular app..."
      - npm --prefix app run build --configuration=production

  post_build:
    commands:
      - echo "Packaging the build artifacts..."
      - mkdir -p deploy
      - zip -r deploy/app.zip app/dist/app/
      - ls -l deploy
      - echo "Creating deployment artifacts for S3..."

artifacts:
  files:
    - 'deploy/app.zip' 
  discard-paths: yes 

cache:
  paths:
    - app/node_modules/**/*  