version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix app

  build:
    commands:
      - echo "Building the Angular app..."
      - npm --prefix app run build -- --configuration production

  post_build:
    commands:
      - echo "Checking if build directory exists..."
      - ls -la app/dist/ 
      - ls -la app/dist/aws-chat/ || echo "Warning: app/dist/aws-chat/ does not exist!"
      - if [ -d "app/dist/aws-chat" ] && [ "$(ls -A app/dist/aws-chat)" ]; then
          echo "Build directory found, proceeding to package...";
          mkdir -p deploy;
          tar -czf deploy/app.tar.gz -C app/dist/aws-chat .;
        else
          echo "ERROR Build directory app/dist/aws-chat/ is missing or empty! Aborting.";
          exit 1;
        fi 

artifacts:
  files:
    - 'deploy/**/*' 
  discard-paths: yes 

cache:
  paths:
    - node_modules/**/*  