version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore

  build:
    commands:
      - echo Building the .NET Lambda function...
      - dotnet build --configuration Release

  post_build:
    commands:
      - echo Publishing the Lambda function...
      - dotnet publish --configuration Release --output ./publish

artifacts:
  files:
    - '**/*'
  base-directory: 'publish'
