version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore server

  build:
    commands:
      - echo Building the .NET Lambda function...
      - dotnet build server --configuration Release

  post_build:
    commands:
      - echo Publishing the Lambda function...
      - dotnet publish server --configuration Release --output ./publish
      - echo "Zipping artifact..."
      - zip -r server.zip ./publish

artifacts:
  files:
    - server.zip
  discard-paths: yes
