version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Setting up environment..."
      - export HOME=/root 
      - export DOTNET_CLI_HOME=/root
      - echo "Installing dependencies..."
      - dotnet restore server.Tests

  build:
    commands:
      - echo "Running tests..."
      - dotnet test server.Tests --configuration Release --logger trx

reports:
  test-reports:
    files:
      - "**/*.trx"
    base-directory: server.Tests/TestResults
    discard-paths: yes
